site_name: Ucupaint
theme: readthedocs
nav:
  - Starting :
    - Introduction : 00.introduction.md
    - Quick Setup : 01.quick-setup.md
  
  - Channels:
    - Channels : 02.00.channels.md
    - Channel Operation : 02.01.channel-operation.md
    - Channel Type : 02.02.channel-type.md
  
  - Layers :
    - Layers : 03.00.layers.md
    - Layer Operation : 03.01.layer-operation.md
    - Layer Type : 03.02.layer-type.md

  - Modifier : 
    - Modifier : 04.00.modifier.md
    - Modifier Operation : 04.01.modifier-operation.md
    - Modifier Type : 04.02.modifier-type.md