site_name: Ucupaint
theme: readthedocs
nav:
  - Starting :
    - Introduction : 00.introduction.md
    - Quick Setup : 01.quick-setup.md
  
  - Channels:
    - Channels : 02.channels.md
  
  - Layers :
    - Layers : 03.00.layers.md
    - Layer Operation : 03.01.layer-operation.md
    - Layer Type : 03.02.layer-type.md

  - Modifier : 04.modifier.md
  